compEng/urls.py
# compEng/urls.py
from django.urls import path
from . import views

app_name = "compEng"

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("", views.landing_view, name="landing"),
    path("home/", views.home_view, name="home"),
    path("registered-users/", views.registered_users_view, name="registered_users"),
    path("delete_mark/<int:mark_id>/", views.delete_mark_view, name="delete_mark"),
    path("update_mark/<int:mark_id>/", views.update_mark_view, name="update_mark"),
    path("logout/", views.logout_view, name="logout"),
]

jdtpoly/urls.py
# myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('compEng.urls')),
]

compEng/models.py
# compEng/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class FacultyUser(AbstractUser):
    name = models.CharField(max_length=255, blank=True)
    phone_number = models.CharField(max_length=15, blank=True)
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return self.username

class StudentMark(models.Model):
    name = models.CharField(max_length=255)
    roll = models.CharField(max_length=10)
    mark1 = models.IntegerField()
    mark2 = models.IntegerField()
    mark3 = models.IntegerField()

    @property
    def total_mark(self):
        return self.mark1 + self.mark2 + self.mark3

    @property
    def pass_fail_status(self):
        total = self.total_mark
        return 'Pass' if total >= 150 else 'Fail'

compEng/forms.py
# compEng/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import FacultyUser
from django import forms
from .models import StudentMark

class UserCreationForm(UserCreationForm):
    class Meta:
        model = FacultyUser
        fields = ['username', 'name', 'phone_number', 'password1', 'password2']

class UserAuthenticationForm(AuthenticationForm):
    class Meta:
        model = FacultyUser
        fields = ['username', 'password']



class StudentMarkForm(forms.ModelForm):
    class Meta:
        model = StudentMark
        fields = ['name', 'roll', 'mark1', 'mark2', 'mark3']

compEng/views.py
# compEng/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.contrib.auth import login
from .forms import UserCreationForm, UserAuthenticationForm
from .models import FacultyUser
from .forms import StudentMarkForm
from .models import StudentMark


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("compEng:home")
        else:
            print(form.errors)
            return render(request, "signup.html", {"form": form})
    else:
        form = UserCreationForm()
    return render(request, "signup.html", {"form": form})


from django.contrib.auth import authenticate, login
from django.http import JsonResponse


def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        # Authenticate user
        print(username, password)
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("compEng:home")
        else:
            return render(
                request,
                "login.html",
                {"message": {"success": False, "message": "Invalid login credentials"}},
            )
            # return JsonResponse({'success': False, 'message': 'Invalid login credentials'})
    else:
        return render(request, "login.html")


def landing_view(request):
    return render(request, "landing.html")


def home_view(request):
    if request.method == "POST":
        form = StudentMarkForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = StudentMarkForm()

    # Retrieve all student marks from the database
    student_marks = StudentMark.objects.all()
    user_info = None
    if request.user.is_authenticated:
        user_info = {
            "username": request.user.username,
            "email": request.user.email,
        }

    return render(
        request,
        "home.html",
        {"form": form, "student_marks": student_marks, "user_info": user_info},
    )


def registered_users_view(request):
    users = FacultyUser.objects.all()
    return render(request, "registered_users.html", {"users": users})


def delete_mark_view(request, mark_id):
    mark = get_object_or_404(StudentMark, id=mark_id)
    mark.delete()
    return redirect("compEng:home")


def update_mark_view(request, mark_id):
    mark = get_object_or_404(StudentMark, id=mark_id)

    if request.method == "POST":
        form = StudentMarkForm(request.POST, instance=mark)
        if form.is_valid():
            form.save()
            return redirect("compEng:home")
    else:
        form = StudentMarkForm(instance=mark)

    student_marks = StudentMark.objects.all()

    return render(
        request,
        "home.html",
        {"form": form, "student_marks": student_marks, "selected_mark_id": mark_id},
    )


def logout_view(request):
    logout(request)
    return redirect("compEng:login")

compEng/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Mark List</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 20px;
            background-color: #f4f4f4;
        }

        h2 {
            color: #333;
            text-align: center;
        }

        form {
            margin-bottom: 20px;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 12px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            background-color: #4CAF50;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

        button:hover {
            background-color: #45a049;
        }

        button a {
            color: white;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }



        th,
        td {
            padding: 15px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #4CAF50;
            color: white;
        }

        a {
            text-decoration: none;
            color: #3498db;
            margin-right: 10px;
        }

        a:hover {
            color: #2980b9;
        }

        h3 {
            color: #333;
            text-align: center;
        }

        .container {
            padding-left: 100px;
            padding-right: 100px;

        }

        .container-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
        }

        .top-bar {
            background-color: #333;
            color: white;
            padding: 10px;
            text-align: right;
        }
        .title-container{
            background-color: #8dc7ed;
            padding: 10px;
      
        }
        .title{
            display: flex;
            justify-content: center;
            font-weight: bolder;
            font-size: xx-large;
        }
        .sub-title{
            display: flex;
            justify-content: center;
            font-weight: bolder;
            font-size: large;
        }
    </style>
</head>

<body>

    <div class="container">

        <div class="top-bar">
            {% if user.is_authenticated %}
            <p>
                Welcome, {{ user.username }} | {{ user.email }}
            </p>
            <p>
                <a href="{% url 'compEng:logout' %}">Logout</a>
            </p>
            {% else %}
            <a href="{% url 'compEng:login' %}">Login</a> | <a href="{% url 'compEng:signup' %}">Sign Up</a>
            {% endif %}
        </div>

        <div class="title-container">
            <P class="title">JDT ISLAM POLYTECHNIC COLLEGE</P>
            <P class="sub-title">COMPUTER ENGINEERING</P>

        </div>

        {% if not selected_mark_id %}
        <h2>Student Mark List</h2>

        <div class="container">
            <form method="post" class="container-grid" action="{% url 'compEng:home' %}">
                {% csrf_token %}
                <div>
                    <label for="name">Name:</label>
                    <input type="text" name="name" id="name" required>
                </div>

                <div>
                    <label for="roll">Roll:</label>
                    <input type="text" name="roll" id="roll" required>
                </div>

                <div>
                    <label for="mark1">Mark 1:</label>
                    <input type="number" name="mark1" id="mark1" required>
                </div>

                <div>
                    <label for="mark2">Mark 2:</label>
                    <input type="number" name="mark2" id="mark2" required>
                </div>

                <div>
                    <label for="mark3">Mark 3:</label>
                    <input type="number" name="mark3" id="mark3" required>
                </div>

                <button type="submit">Submit</button>
            </form>
        </div>
        {% endif %}

        {% if selected_mark_id %}
        <h3>Update Student Mark</h3>
        <div class="container">
            <form method="post" class="container-grid"
                action="{% url 'compEng:update_mark' mark_id=selected_mark_id %}">
                {% csrf_token %}
                <div>
                    <label for="name">Name:</label>
                    <input type="text" name="name" id="name" value="{{ form.instance.name }}" required>
                </div>
                <div>
                    <label for="roll">Roll:</label>
                    <input type="text" name="roll" id="roll" value="{{ form.instance.roll }}" required>
                </div>

                <div>


                    <label for="mark1">Mark 1:</label>
                    <input type="number" name="mark1" id="mark1" value="{{ form.instance.mark1 }}" required>
                </div>
                <div>

                    <label for="mark2">Mark 2:</label>
                    <input type="number" name="mark2" id="mark2" value="{{ form.instance.mark2 }}" required>
                </div>

                <div>
                    <label for="mark3">Mark 3:</label>
                    <input type="number" name="mark3" id="mark3" value="{{ form.instance.mark3 }}" required>
                </div>

                <button type="submit">Update</button>
            </form>
        </div>

        {% endif %}

        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Roll</th>
                    <th>Mark 1</th>
                    <th>Mark 2</th>
                    <th>Mark 3</th>
                    <th>Total Mark</th>
                    <th>Pass/Fail</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for student_mark in student_marks %}
                <tr>
                    <td>{{ student_mark.name }}</td>
                    <td>{{ student_mark.roll }}</td>
                    <td>{{ student_mark.mark1 }}</td>
                    <td>{{ student_mark.mark2 }}</td>
                    <td>{{ student_mark.mark3 }}</td>
                    <td>{{ student_mark.total_mark }}</td>
                    <td>{{ student_mark.pass_fail_status }}</td>
                    <td>
                        <button>
                            <a href="{% url 'compEng:update_mark' mark_id=student_mark.id %}">Update</a>
                        </button>
                    </td>
                    <td>
                        <button>
                            <a href="{% url 'compEng:delete_mark' mark_id=student_mark.id %}">Delete</a>
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</body>

</html>

compEng/templates/landing.html
<!-- compEng/templates/compEng/landing.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to My Site</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
            text-align: center;
        }

        .landing-page {
            background-color: #fff;
            max-width: 600px;
            margin-top: 200px !important;
            margin: 50px auto;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #333;
        }

        p {
            color: #555;
        }

        .landing-buttons {
            margin-top: 20px;
        }

        a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        a:hover {
            background-color: #0056b3;
        }
        .title-container{
            background-color: #8dc7ed;
            padding: 10px;
      
        }
        .title{
            display: flex;
            justify-content: center;
            font-weight: bolder;
            font-size: xx-large;
        }
        .sub-title{
            display: flex;
            justify-content: center;
            font-weight: bolder;
            font-size: large;
        }
    </style>
</head>
<body>

    <div class="title-container">
        <P class="title">JDT ISLAM POLYTECHNIC COLLEGE</P>
        <P class="sub-title">COMPUTER ENGINEERING</P>

    </div>
    <div class="landing-page">
        <h1>Welcome to JDT Islam Polytechnic College</h1>
        <p>Explore Django! WebApplication</p>

        <div class="landing-buttons">
            <a href="{% url 'compEng:login' %}">Login</a>
            <a href="{% url 'compEng:signup' %}">Sign Up</a>
        </div>
    </div>
</body>
</html>

compEng/templates/login.html
<!-- compEng/templates/compEng/login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
            text-align: center;
        }

        .login-container {
            background-color: #fff;
            max-width: 400px;
            margin: 50px auto;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #333;
        }

        form {
            margin-top: 20px;
            text-align: left;
        }

        label {
            display: block;
            margin-bottom: 8px;
            color: #555;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }

        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        button:hover {
            background-color: #0056b3;
        }
        .error{
            background-color: lightcoral;
            padding: 2%;
        }
        .title-container{
            background-color: #8dc7ed;
            padding: 10px;
      
        }
        .title{
            display: flex;
            justify-content: center;
            font-weight: bolder;
            font-size: xx-large;
        }
        .sub-title{
            display: flex;
            justify-content: center;
            font-weight: bolder;
            font-size: large;
        }
    </style>
</head>
<body>

    <div class="title-container">
        <P class="title">JDT ISLAM POLYTECHNIC COLLEGE</P>
        <P class="sub-title">COMPUTER ENGINEERING</P>

    </div>
    <div class="login-container">
        <h1>Login</h1>
        <form method="post" action="{% url 'compEng:login' %}">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" id="username" required>

            <label for="password">Password:</label>
            <input type="password" name="password" id="password" required>

            <button type="submit">Login</button>
        </form>
        <p class="error">
            {% if message %}
                        Success: {{  message.success }}<br>
                        Message : {{  message.message }}<br>
            {% endif %}
        </p>
    </div>
</body>
</html>

compEng/templates/registered_users.html
<!-- compEng/templates/registered_users.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registered Users</title>
    <style>
             .title-container{
            background-color: #8dc7ed;
            padding: 10px;
      
        }
        .title{
            display: flex;
            justify-content: center;
            font-weight: bolder;
            font-size: xx-large;
        }
        .sub-title{
            display: flex;
            justify-content: center;
            font-weight: bolder;
            font-size: large;
        }
    </style>
</head>
<body>

    <div class="title-container">
        <P class="title">JDT ISLAM POLYTECHNIC COLLEGE</P>
        <P class="sub-title">COMPUTER ENGINEERING</P>

    </div>
    <h1>Registered Users</h1>
    <ul>
        {% for user in users %}
            <li>{{ user.username }} - {{ user.email }}</li>
        {% endfor %}
    </ul>
</body>
</html>

compEng/templates/signup.html
<!-- compEng/templates/compEng/signup.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
            text-align: center;
        }

        .signup-container {
            background-color: #fff;
            max-width: 400px;
            margin: 50px auto;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #333;
        }

        form {
            margin-top: 20px;
            text-align: left;
        }

        label {
            display: block;
            margin-bottom: 8px;
            color: #555;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }

        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        button:hover {
            background-color: #0056b3;
        }
        .error{
            background-color: lightcoral;
            padding: 2%;
        }
        .title-container{
            background-color: #8dc7ed;
            padding: 10px;
      
        }
        .title{
            display: flex;
            justify-content: center;
            font-weight: bolder;
            font-size: xx-large;
        }
        .sub-title{
            display: flex;
            justify-content: center;
            font-weight: bolder;
            font-size: large;
        }
    </style>
</head>
<body>

    <div class="title-container">
        <P class="title">JDT ISLAM POLYTECHNIC COLLEGE</P>
        <P class="sub-title">COMPUTER ENGINEERING</P>

    </div>
    <div class="signup-container">
        <h1>Sign Up</h1>
        <form method="post" action="{% url 'compEng:signup' %}">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" id="username" required>

            <label for="name">Name:</label>
            <input type="text" name="name" id="name" required>

            <label for="phone_number">Phone Number:</label>
            <input type="text" name="phone_number" id="phone_number" required>

            <label for="password1">Password:</label>
            <input type="password" name="password1" id="password1" required>

            <label for="password2">Confirm Password:</label>
            <input type="password" name="password2" id="password2" required>

            <button type="submit">Sign Up</button>

        </form>
        <p class="error">
            {% if form.errors %}
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        {{ field }}: {{ error }}<br>
                    {% endfor %}
                {% endfor %}
            {% endif %}
        </p>
    </div>
</body>
</html>